### ISSUE TITLE
Sync Target Attribute and Instance Identifier

### ISSUE THREAD

**Issue by manankalra** [erasmoartur/attribute-radviz#2]
This is an extension to #1 which I tried to fix by commenting out [Line 883](https://github.com/erasmoartur/attribute-radviz/blob/master/DualRadViz.html#L883). Turns out there's more to it than not disabling the _setlab_ attribute when you select a different value from the drop-down.

The selected instance identifier is [removed](https://github.com/erasmoartur/attribute-radviz/blob/master/DualRadViz.html#L876) from the attribute view as this happens (which should happen). After the changes I made to fix #1, I guess the sliced list is further reduced on selecting a different instance identifier. Thus, it keeps no track of previous removals which should now be added back to the attribute view. Ideally, rather than removing an item from the current list, the list should be populated with all labels except the instance identifier selected by the user. 

Also, as it's possible to make changes to the Target attribute - the selected instance identifier comes back up in the attribute view if the current Target attribute is deselected and selected again further leading to the data view going blank.

Quoting from the [Attribute-Radviz paper](https://sol.sbc.org.br/index.php/sibgrapi/article/view/9817) - "_one single dataset can encode more than one phenomenon that may be governed by distinct subsets of attributes_", the requirement to make both these drop-downs editable is legit.

Generally, it only makes sense looking at both the views together if the Target Attribute and Instance Identifier are the same. So, a single solution to everything will be to sync both of them and re-render both the views as the user changes any one of them.

**Comment by erasmoartur** [comment]
The tool's data handling is a bit messy due to how it grew and was implemented. As an experimental tool, everything was implemented in a prototype strategy, since each requested demand used to be fastly developed, presented, and tested so that we could decide whether to adopt it or not. The problem is that the rewriting phase, which is mandatory in prototyping strategies, has never been performed.

But let's take a look at this issue:

Since both views can be re-rendered at any time, the data from the CSV file is always unchanged in the variable _data_.

The variable _radvizData_ stores the correlations of each attribute against the labels, and we split the target one from the list. It should be recomputed every time the view is re-rendered.

Same for the variable _regularData_ in the second view. 

The problem is: before sending the data for the second RadViz module, we split from the data the target attribute and the identifier one (just one if they are the same). 

To make the change of the identifier feasible, we have to change the second RadViz module to make it known on the fly the attribute used as an identifier. Also, the attribute used as ID was initially removed from the _regularData_ variable because I was assuming that there would always exist an exclusive attribute for that in the data set, but in practice, this is not what happens.

I'm doing the changes right now...

Edit:
You are right. The solution seems to be making both views render again together (sync). However, I am afraid of the processing demand with large data sets.

**Comment by manankalra** [comment]
I'm not sure if this is going to have any negative impact on processing times as compared to what is happening now.

What I'm proposing is:
- Remove the drop-down for the Instance Identifier.
- After the user selects the Target Attribute, render both the views. Data View renders as if the Instance Identifier is the Target Attribute with default parameters as already set in the sidebar.
- The Target Attribute still remains editable. On any change to it, both views are rendered again like the previous step. However, the sidebar changes made by the user could be saved.
- On interacting with the Attribute View, the tool behaves in the same way as it does now.
- On making any changes using the sidebar, the tool behaves in the same way as it does now.

There might be tied-up complications with it which I don't have an idea about. I'll see to it and try to understand the current behavior.

**Comment by erasmoartur** [comment]
This is a good idea, and I should have done this earlier. But, I think the issue is fixed now.

I changed in [Line 879](https://github.com/erasmoartur/attribute-radviz/blob/master/DualRadViz.html#L879) the variables _firstRun_ and _sampleChange_. These variables are flags that prevent each rendering of the second view from being fully recomputed again. So, in this case, I'm forcing the second view to be, in fact, recomputed.

I also implemented the _hideIDAttr_ method in the RadViz module of the attribute view _(/files/radviz-component.js)_, which hides only the chosen attribute.

I ran some tests, and it seems to work fine.

**Comment by manankalra** [comment]
Yeah, it works fine. Thank you.

Other than this, as I mentioned in https://github.com/erasmoartur/attribute-radviz/issues/2#issue-617711601:
> Also, as it's possible to make changes to the Target attribute - the selected instance identifier comes back up in the attribute view if the current Target attribute is deselected and selected again further leading to the data view going blank.

This still happens. However, I don't think it's important to fix it now. Just mentioning it here if there's a plan to improve the tool in the future.

Steps to replicate (Zoo dataset):
- Target Attribute: _class_size_, Instance Identifier: _class_size_
- Change Instance Identifier to _fins_ which results in it disappearing from the Attribute View.
- Change Target Attribute to anything other than _class_size_
- Change Target Attribute back to _class_size_

_fins_ comes back up in the Attribute View even though it's the Instance Identifier. Also, if we now move the cursor onto _fins_, the Data View goes blank  as shown below.

![Screenshot 2020-05-16 at 4 26 50 PM](https://user-images.githubusercontent.com/12759088/82123644-57116a80-9792-11ea-9a20-8862fe785bee.png)

**Comment by erasmoartur** [comment]
I believe it is fixed now. I made a small update to the function of [Line 868](https://github.com/erasmoartur/attribute-radviz/blob/master/DualRadViz.html#L868).
